C-Helper
========
:author: Martin Horauer
:doctype: book
:toc: left
:toclevels: 2
:toc-title: C-Helper
:icons: font
:data-uri:
:lang: en
:encoding: utf-8
:nofooter:

About & Overview
----------------
link:002_about.html[about]         |
link:005_ansi-c.html[ANSI-C Index]

assert.h
--------
link:010_assert.html[assert]

ctype.h
-------
link:020_isalnum.html[isalnum]   |
link:021_isalpha.html[isalpha]   |
link:022_iscntrl.html[iscntrl]   |
link:023_isdigit.html[isdigit]   |
link:024_isgraph.html[isgraph]   |
link:025_islower.html[islower]   |
link:026_isprint.html[isprint]   |
link:027_ispunct.html[ispunct]   |
link:028_isspace.html[isspace]   |
link:029_isupper.html[isupper]   |
link:030_isxdigit.html[isxdigit] |
link:031_tolower.html[tolower]   |
link:033_toupper.html[toupper]

errno.h
-------
link:040_errno.html[errno]

floats.h
--------
link:050_float.html[float]


limits.h
--------
link:060_limits.html[limits]

locale.h
--------
link:070_setlocale.html[setlocale]

math.h
------
link:080_acos.html[acos]   |
link:081_asin.html[asin]   |
link:082_atan.html[atan]   |
link:083_atan2.html[atan2] |
link:084_ceil.html[ceil]   |
link:085_cos.html[cos]     |
link:086_cosh.html[cosh]   |
link:087_exp.html[exp]     |
link:088_fabs.html[fabs]   |
link:089_floor.html[floor] |
link:090_fmod.html[fmod]   |
link:091_frexp.html[frexp] |
link:092_ldexp.html[ldexp] |
link:093_log.html[log]     |
link:094_log10.html[log10] |
link:095_modf.html[modf]   |
link:096_pow.html[pow]     |
link:097_sin.html[sin]     |
link:098_sinh.html[sinh]   |
link:099_sqrt.html[sqrt]   |
link:100_tan.html[tan]     |
link:101_tanh.html[tanh]

setjmp.h
--------
link:120_longjmp.html[longjmp] |
link:121_setjmp.html[setjmp]


signal.h
--------
link:130_signal.html[signal] |
link:131_raise.html[raise]


stdarg.h
--------
link:140_stdarg.html[stdarg]


stddef.h
--------
link:150_stddef.html[stddef]


stdio.h
-------
link:159_stdio_summary.html[STDIO Summary]|
link:160_clearerr.html[clearerr]          |
link:161_fclose.html[fclose]              |
link:162_feof.html[feof]                  |
link:162_ferror.html[ferror]              |
link:163_fflush.html[fflush]              |
link:164_fgetc.html[fgetc]                |
link:165_fgetpos.html[fgetpos]            |
link:166_fgets.html[fgets]                |
link:167_fopen.html[fopen]                |
link:168_fprintf.html[fprintf]            |
link:169_fputc.html[fputc]                |
link:170_fputchar.html[fputchar]          |
link:171_fputs.html[fputs]                |
link:172_fread.html[fread]                |
link:173_freopen.html[freopen]            |
link:174_fscanf.html[fscanf]              |
link:175_fseek.html[fseek]                |
link:176_fsetpos.html[fsetpos]            |
link:177_ftell.html[ftell]                |
link:178_fwrite.html[fwrite]              |
link:179_getc.html[getc]                  |
link:180_getchar.html[getchar]            |
link:181_perror.html[perror]              |
link:182_printf.html[printf]              |
link:183_putc.html[putc]                  |
link:184_putchar.html[putchar]            |
link:185_puts.html[puts]                  |
link:186_remove.html[remove]              |
link:187_rename.html[rename]              |
link:188_rewind.html[rewind]              |
link:189_scanf.html[scanf]                |
link:190_setbuf.html[setbuf]              |
link:191_setvbuf.html[setvbuf]            |
link:192_sprintf.html[sprintf]            |
link:193_snprintf.html[snprintf]          |
link:193_sscanf.html[sscanf]              |
link:194_tmpfile.html[tmpfile]            |
link:195_tmpnam.html[tmpnam]              |
link:196_ungetc.html[ungetc]              |
link:197_vfprintf.html[vfprintf]          |
link:198_vprintf.html[vprintf]            |
link:199_vsnprintf.html[vsnprintf]        |
link:200_vsprintf.html[vsprintf]          |
link:201_vfscanf.html[vfscanf]            |
link:202_vscanf.html[vscanf]              |
link:203_vsscanf.html[vsscanf]

stdlib.h
--------
link:249_stdlib_summary.html[STDLIB Summary]|
link:250_abort.html[abort]                  |
link:251_abs.html[abs]                      |
link:252_atexit.html[atexit]                |
link:253_atof.html[atof]                    |
link:254_atoi.html[atoi]                    |
link:255_atol.html[atol]                    |
link:256_bsearch.html[bsearch]              |
link:257_calloc.html[calloc]                |
link:258_div.html[div]                      |
link:259_ldiv.html[ldiv]                    |
link:260_exit.html[exit]                    |
link:261_free.html[free]                    |
link:262_getenv.html[getenv]                |
link:263_labs.html[labs]                    |
link:264_malloc.html[malloc]                |
link:265_mblen.html[mblen]                  |
link:266_mbstowcs.html[mbstowcs]            |
link:267_mbtowc.html[mbtowc]                |
link:268_qsort.html[qsort]                  |
link:269_rand.html[rand]                    |
link:270_realloc.html[realloc]              |
link:271_srand.html[srand]                  |
link:272_strtod.html[strtod]                |
link:273_strtol.html[strtol]                |
link:274_strtoul.html[strtoul]              |
link:275_system.html[system]                |
link:276_wcstombs.html[wcstombs]            |
link:277_wctomb.html[wctomb]

string.h
--------
link:300_memchr.html[memchr]     |
link:301_memcmp.html[memcmp]     |
link:302_memcpy.html[memcpy]     |
link:303_memmove.html[memmove]   |
link:304_memset.html[memset]     |
link:305_strcat.html[strcat]     |
link:306_strchr.html[strchr]     |
link:307_strcmp.html[strcmp]     |
link:308_strcoll.html[strcoll]   |
link:309_strcpy.html[strcpy]     |
link:310_strcspn.html[strcspn]   |
link:311_strerror.html[strerror] |
link:312_strlen.html[strlen]     |
link:313_strncat.html[strncat]   |
link:314_strncmp.html[strncmp]   |
link:315_strncpy.html[strncpy]   |
link:316_strpbrk.html[strpbrk]   |
link:317_strrchr.html[strrchr]   |
link:318_strspn.html[strspn]     |
link:319_strstr.html[strstr]     |
link:320_strtok.html[strtok]     |
link:321_strxfrm.html[strxfrm]

time.h
------
link:349_time_summary.html[TIME Summary] |
link:350_asctime.html[asctime]           |
link:351_clock.html[clock]               |
link:352_ctime.html[ctime]               |
link:353_difftime.html[difftime]         |
link:354_gmtime.html[gmtime]             |
link:355_localtime.html[localtime]       |
link:356_mktime.html[mktime]             |
link:357_strftime.html[strftime]         |
link:358_time.html[time]

ASCII Table
-----------
link:500_ascii-table.html[ASCII Table]
