C-Helper
========
:author: Martin Horauer
:doctype: book
:toc: left
:toclevels: 2
:toc-title: C-Helper
:icons: font
:data-uri:
:lang: en
:encoding: utf-8

About & Overview
----------------
link:002_about.asciidoc[]
link:005_ansi-c.asciidoc[]

assert.h
--------
link:010_assert.asciidoc[]

ctype.h
-------
link:020_isalnum.asciidoc[]
link:021_isalpha.asciidoc[]
link:022_iscntrl.asciidoc[]
link:023_isdigit.asciidoc[]
link:024_isgraph.asciidoc[]
link:025_islower.asciidoc[]
link:026_isprint.asciidoc[]
link:027_ispunct.asciidoc[]
link:028_isspace.asciidoc[]
link:029_isupper.asciidoc[]
link:030_isxdigit.asciidoc[]
link:031_tolower.asciidoc[]
link:033_toupper.asciidoc[]

errno.h
-------
link:040_errno.asciidoc[]

floats.h
--------
link:050_float.asciidoc[]


limits.h
--------
link:060_limits.asciidoc[]

locale.h
--------
link:070_setlocale.asciidoc[]

math.h
------
link:080_acos.asciidoc[]
link:081_asin.asciidoc[]
link:082_atan.asciidoc[]
link:083_atan2.asciidoc[]
link:084_ceil.asciidoc[]
link:085_cos.asciidoc[]
link:086_cosh.asciidoc[]
link:087_exp.asciidoc[]
link:088_fabs.asciidoc[]
link:089_floor.asciidoc[]
link:090_fmod.asciidoc[]
link:091_frexp.asciidoc[]
link:092_ldexp.asciidoc[]
link:093_log.asciidoc[]
link:094_log10.asciidoc[]
link:095_modf.asciidoc[]
link:096_pow.asciidoc[]
link:097_sin.asciidoc[]
link:098_sinh.asciidoc[]
link:099_sqrt.asciidoc[]
link:100_tan.asciidoc[]
link:101_tanh.asciidoc[]

setjmp.h
--------
link:120_longjmp.asciidoc[]
link:121_setjmp.asciidoc[]


signal.h
--------
link:130_signal.asciidoc[]
link:131_raise.asciidoc[]


stdarg.h
--------
link:140_stdarg.asciidoc[]


stddef.h
--------
link:150_stddef.asciidoc[]


stdio.h
-------
link:159_stdio_summary.asciidoc[]
link:160_clearerr.asciidoc[]
link:161_fclose.asciidoc[]
link:162_feof.asciidoc[]
link:162_ferror.asciidoc[]
link:163_fflush.asciidoc[]
link:164_fgetc.asciidoc[]
link:165_fgetpos.asciidoc[]
link:166_fgets.asciidoc[]
link:167_fopen.asciidoc[]
link:168_fprintf.asciidoc[]
link:169_fputc.asciidoc[]
link:170_fputchar.asciidoc[]
link:171_fputs.asciidoc[]
link:172_fread.asciidoc[]
link:173_freopen.asciidoc[]
link:174_fscanf.asciidoc[]
link:175_fseek.asciidoc[]
link:176_fsetpos.asciidoc[]
link:177_ftell.asciidoc[]
link:178_fwrite.asciidoc[]
link:179_getc.asciidoc[]
link:180_getchar.asciidoc[]
link:181_perror.asciidoc[]
link:182_printf.asciidoc[]
link:183_putc.asciidoc[]
link:184_putchar.asciidoc[]
link:185_puts.asciidoc[]
link:186_remove.asciidoc[]
link:187_rename.asciidoc[]
link:188_rewind.asciidoc[]
link:189_scanf.asciidoc[]
link:190_setbuf.asciidoc[]
link:191_setvbuf.asciidoc[]
link:192_sprintf.asciidoc[]
link:193_snprintf.asciidoc[]
link:193_sscanf.asciidoc[]
link:194_tmpfile.asciidoc[]
link:195_tmpnam.asciidoc[]
link:196_ungetc.asciidoc[]
link:197_vfprintf.asciidoc[]
link:198_vprintf.asciidoc[]
link:199_vsnprintf.asciidoc[]
link:200_vsprintf.asciidoc[]
link:201_vfscanf.asciidoc[]
link:202_vscanf.asciidoc[]
link:203_vsscanf.asciidoc[]

stdlib.h
--------
link:249_stdlib_summary.asciidoc[]
link:250_abort.asciidoc[]
link:251_abs.asciidoc[]
link:252_atexit.asciidoc[]
link:253_atof.asciidoc[]
link:254_atoi.asciidoc[]
link:255_atol.asciidoc[]
link:256_bsearch.asciidoc[]
link:257_calloc.asciidoc[]
link:258_div.asciidoc[]
link:259_ldiv.asciidoc[]
link:260_exit.asciidoc[]
link:261_free.asciidoc[]
link:262_getenv.asciidoc[]
link:263_labs.asciidoc[]
link:264_malloc.asciidoc[]
link:265_mblen.asciidoc[]
link:266_mbstowcs.asciidoc[]
link:267_mbtowc.asciidoc[]
link:268_qsort.asciidoc[]
link:269_rand.asciidoc[]
link:270_realloc.asciidoc[]
link:271_srand.asciidoc[]
link:272_strtod.asciidoc[]
link:273_strtol.asciidoc[]
link:274_strtoul.asciidoc[]
link:275_system.asciidoc[]
link:276_wcstombs.asciidoc[]
link:277_wctomb.asciidoc[]

string.h
--------
link:300_memchr.asciidoc[]
link:301_memcmp.asciidoc[]
link:302_memcpy.asciidoc[]
link:303_memmove.asciidoc[]
link:304_memset.asciidoc[]
link:305_strcat.asciidoc[]
link:306_strchr.asciidoc[]
link:307_strcmp.asciidoc[]
link:308_strcoll.asciidoc[]
link:309_strcpy.asciidoc[]
link:310_strcspn.asciidoc[]
link:311_strerror.asciidoc[]
link:312_strlen.asciidoc[]
link:313_strncat.asciidoc[]
link:314_strncmp.asciidoc[]
link:315_strncpy.asciidoc[]
link:316_strpbrk.asciidoc[]
link:317_strrchr.asciidoc[]
link:318_strspn.asciidoc[]
link:319_strstr.asciidoc[]
link:320_strtok.asciidoc[]
link:321_strxfrm.asciidoc[]

time.h
------
link:349_time_summary.asciidoc[]
link:350_asctime.asciidoc[]
link:351_clock.asciidoc[]
link:352_ctime.asciidoc[]
link:353_difftime.asciidoc[]
link:354_gmtime.asciidoc[]
link:355_localtime.asciidoc[]
link:356_mktime.asciidoc[]
link:357_strftime.asciidoc[]
link:358_time.asciidoc[]
link:500_ascii-table.asciidoc[]
